#  _____            _ _        _____ __  __ _____
# |_   _|          (_) |      / ____|  \/  |  __ \
#   | |  _ ____   ___| |_ ___| (___ | \  / | |__) |
#   | | | '_ \ \ / / | __/ _ \\___ \| |\/| |  ___/
#  _| |_| | | \ V /| | ||  __/____) | |  | | |
# |_____|_| |_|\_/ |_|\__\___|_____/|_|  |_|_|
#
# By Atzer.