#  _____            _ _        _____ __  __ _____
# |_   _|          (_) |      / ____|  \/  |  __ \
#   | |  _ ____   ___| |_ ___| (___ | \  / | |__) |
#   | | | '_ \ \ / / | __/ _ \\___ \| |\/| |  ___/
#  _| |_| | | \ V /| | ||  __/____) | |  | | |
# |_____|_| |_|\_/ |_|\__\___|_____/|_|  |_|_|
#
# By Atzer.

database:
  host: localhost
  port: 3306
  name: "database_name"
  user: "database_user"
  password: "database_password"
  pool:
    max_pool_size: 10
    minimum_idle: 2
    max_lifetime: 1800000
    connection_timeout: 5000
